# Generated by Django 3.2.4 on 2023-06-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnsync_app', '0003_category_tag_thesispaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social_site_urls',
            field=models.URLField(blank=True),
        ),
    ]
