# Generated by Django 3.2.4 on 2023-06-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnsync_app', '0004_alter_userprofile_social_site_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('file', models.FileField(upload_to='research_papers/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(to='learnsync_app.UserProfile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnsync_app.category')),
                ('tags', models.ManyToManyField(to='learnsync_app.Tag')),
            ],
        ),
    ]
