# Generated by Django 3.2.4 on 2023-07-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnsync_app', '0006_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='thesispaper',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='thesispaper',
            name='references',
            field=models.TextField(blank=True),
        ),
    ]
