# Generated by Django 3.2.4 on 2023-07-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnsync_app', '0007_auto_20230714_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchpaper',
            old_name='published_date',
            new_name='publication_date',
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='abstract',
            field=models.TextField(blank=True),
        ),
    ]
