# Generated by Django 3.2.4 on 2023-07-24 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learnsync_app', '0008_auto_20230716_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='thesispaper',
            name='likes',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='references',
        ),
        migrations.RemoveField(
            model_name='thesispaper',
            name='references',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.AddField(
            model_name='reference',
            name='research_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_references', to='learnsync_app.researchpaper'),
        ),
        migrations.AddField(
            model_name='reference',
            name='thesis_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_references', to='learnsync_app.thesispaper'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='authors',
            field=models.ManyToManyField(related_name='research_papers', to='learnsync_app.Author'),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='research_papers', to='learnsync_app.Reference'),
        ),
        migrations.AlterField(
            model_name='thesispaper',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnsync_app.author'),
        ),
        migrations.AddField(
            model_name='thesispaper',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='thesis_papers', to='learnsync_app.Reference'),
        ),
    ]
