# Generated by Django 3.2.4 on 2023-07-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnsync_app', '0009_auto_20230724_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='research_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_references', to='learnsync_app.researchpaper'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='thesis_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thesis_references', to='learnsync_app.thesispaper'),
        ),
    ]
