# Generated by Django 4.2.3 on 2023-08-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnsync_app', '0010_auto_20230724_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='affiliation',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
    ]
